site_name: 'Documentatie'
copyright: Copyright &copy; 2025 LitterApp Gemeenschap
docs_dir: '../../docs/nl'                           # Where to find the Dutch markdown files
site_dir: '../../generated/nl'                      # Where to put the Dutch HTML files

theme:
  name: material
  custom_dir: '../../overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/logo.png                    # The logo is shared by all languages
  favicon: assets/images/favicon.ico              # The favicon is shared by all languages
  language: nl                                    # The build's language
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    #- navigation.indexes
    #- navigation.sections
    #- navigation.tabs
    #- navigation.top
    #- navigation.instant
    #- navigation.tracking

extra_css:
  - assets/stylesheets/littertagger.css             # CSS is shared by all languages

extra:
  alternate:                                        # Language Selection
    - name: English
      link: /en/
      lang: en
    - name: Nederlands
      link: /nl/
      lang: nl
    - name: Fran√ßais
      link: /fr/
      lang: fr
    - name: Deutsch
      link: /de/
      lang: de
  homepage: https://docs.litterapp.net

plugins:
  - search:                                         
      lang: nl                                      # Set language for search

nav:
- Welkom: index.md
- Over ons:
    - Onze missie en visie: 05_Mission-Vision.md
    - Wie zijn we: 08_Who-Are-We.md
- En beginnen maar:
    - Aanmaken gebruiker en profiel vullen: 10_Profile.md
    - Het nemen van foto's: 20_Taking-Pictures.md
    - Het uploaden van foto's: 30_Uploading-Pictures.md
    - Tagging pictures:
        - Regular: 40_Tagging-Pictures.md
        - ShortCuts: 45_Tagging-with-ShortCuts.md
    - Voorbeelden:
      - Tagging voorbeelden: 90_Tagging-Examples.md
      - Item voorbeelden: 92_Item-Examples.md
    - Bevindingen melden: 90_Issues.md
- Video Handleidingen: 60_Video-Tutorials.md
- Succes-verhalen: 
    - Introductie: 50_Events.md
    - Plastic Peukmeuk: 50_PeukMeuk.md
    - De Treasure Hunt: 50_TreasureHunt.md
    - Plastic Avengers, SuckSack: 50_SuckSack.md
    - Plastic Avengers, Nationale Prullenbak Telling: 50_NPT.md
    - Cable Ties: 50_tiewraps-in-Steenwijk.md
    - Statiegeld Alliantie: 50_StatiegeldAlliantie.md
    - De club van 10.000: 50_The10000Club.md
- Veel Gestelde Vragen (FAQ): 90_Faq.md
- Contact: 90_Contact.md
- Support: 95_Support.md
- Functionality (in detail)/TestPlan: 99_Functionality Manual Testplan.md
